export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"

export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT"
export const GET_ONE_PRODUCT_SUCCESS = "GET_ONE_PRODUCT_SUCCESS"
export const GET_ONE_PRODUCT_ERROR = "GET_ONE_PRODUCT_ERROR"

export const INITIAL_PRODUCT = "INITIAL_PRODUCT"